name = "Archè"
license = "MIT"
licenselink = ""
description = "Tema personalizzato per Archè - Il Vuoto"
tags = ["blog", "minimal", "dark"]
features = ["responsive", "animations"]
min_version = "0.100.0"

[author]
  name = "Sandro Lain"
